[package]
name = "gauss"
version = "0.1.0"
edition = "2021"

[[bin]]  # <----- Adicione esta linha
name = "gauss"  # Nome do executável
path = "gauss.rs"  # Caminho para o código

[dependencies]
rand = "0.8.5"
winapi = { version = "0.3.9", features = ["processthreadsapi", "winbase"] }